Stop early in case of error. Only download the bootstrap compiler when needed.

diff --git a/tester/Project b/tester/Project
--- a/tester/Project
+++ b/tester/Project
@@ -1,8 +1,11 @@
 #! /bin/sh
 
+# Stop on errors
+set -e
+
 if [ ! -r Nice ]; then
   cvs -d:pserver:anonymous@$CVS_SOURCEFORGE:/cvsroot/nice export -rHEAD Nice
+  wget -O Nice/external/nice-bootstrap.jar http://nice.sf.net/nice.jar
 fi
-wget -O Nice/external/nice-bootstrap.jar http://nice.sf.net/nice.jar
 
 cd Nice && make world
